language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
branches:
    only:
        - master
install: pip install requests coveralls
script: nosetests --with-coverage --cover-package=freshdesk
after_success: coverage
